#!/usr/bin/env bash
# create_env.sh — Creates an isolated sandbox environment
# Usage: ./create_env.sh <name> [ttl_minutes]
# Example: ./create_env.sh myapp 60

set -euo pipefail

# ── Arguments ────────────────────────────────────────────────────────────────
ENV_NAME="${1:-}"
TTL_MINUTES="${2:-30}"

if [ -z "$ENV_NAME" ]; then
    echo "Usage: $0 <name> [ttl_minutes]"
    exit 1
fi

# ── Generate unique environment ID ───────────────────────────────────────────
# Uses random hex to ensure uniqueness even with the same name
# Format: env-<name>-<6 random hex chars>
ENV_ID="env-${ENV_NAME}-$(openssl rand -hex 3)"

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENVS_DIR="$PROJECT_ROOT/envs"
NGINX_CONF_DIR="$PROJECT_ROOT/nginx/conf.d"
LOGS_DIR="$PROJECT_ROOT/logs/$ENV_ID"

# ── Calculate timestamps ──────────────────────────────────────────────────────
CREATED_AT=$(date -u +%s)
# TTL in seconds
TTL_SECONDS=$((TTL_MINUTES * 60))
EXPIRES_AT=$((CREATED_AT + TTL_SECONDS))

# ── Port allocation ───────────────────────────────────────────────────────────
# Find a free port between 10000-19999 for this environment
# Each environment gets its own port — nothing is hardcoded
find_free_port() {
    python3 -c "
import socket
import random
for _ in range(100):
    port = random.randint(10000, 19999)
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(1)
    result = sock.connect_ex(('localhost', port))
    sock.close()
    if result != 0:
        print(port)
        exit(0)
print('ERROR: No free ports', file=__import__('sys').stderr)
exit(1)
"
}

APP_PORT=$(find_free_port)

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Creating sandbox environment"
echo "  ID:      $ENV_ID"
echo "  Name:    $ENV_NAME"
echo "  TTL:     ${TTL_MINUTES} minutes"
echo "  Port:    $APP_PORT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Create log directory ──────────────────────────────────────────────────────
mkdir -p "$LOGS_DIR"

# ── Create dedicated Docker network ──────────────────────────────────────────
# Every environment gets its own network for isolation
# Containers in different environments cannot talk to each other
echo "→ Creating Docker network: $ENV_ID"
docker network create "$ENV_ID" > /dev/null

# ── Start the app container ───────────────────────────────────────────────────
# Key decisions:
# - Label with sandbox.env=$ENV_ID for easy filtering
# - NOT exposed to host directly — Nginx proxies to it
# - Connected to both the env network and the platform network
echo "→ Starting app container..."
CONTAINER_ID=$(docker run -d \
    --name "${ENV_ID}-app" \
    --network "$ENV_ID" \
    --label "sandbox.env=$ENV_ID" \
    --label "sandbox.name=$ENV_NAME" \
    -e "ENV_ID=$ENV_ID" \
    -e "ENV_NAME=$ENV_NAME" \
    sandbox-app:latest)

# Connect container to platform network so Nginx can reach it
docker network connect platform-network "${ENV_ID}-app"

echo "  ✓ Container started: ${CONTAINER_ID:0:12}"

# ── Start log shipping ────────────────────────────────────────────────────────
# Approach A — stream docker logs to a file
# Store the PID so we can kill it on destroy
echo "→ Starting log shipping..."
docker logs -f "$CONTAINER_ID" >> "$LOGS_DIR/app.log" 2>&1 &
LOG_PID=$!
echo $LOG_PID > "$LOGS_DIR/log_shipper.pid"
echo "  ✓ Log shipper PID: $LOG_PID"

# ── Write Nginx config ────────────────────────────────────────────────────────
# Each environment gets its own virtual host
# Path-based routing: /env/$ENV_ID/ → app container
echo "→ Writing Nginx config..."
cat > "$NGINX_CONF_DIR/${ENV_ID}.conf" << NGINX_EOF
# Auto-generated by create_env.sh for environment: $ENV_ID
# Do not edit manually

server {
    listen 80;
    server_name _;

    location /env/$ENV_ID/ {
        proxy_pass http://${ENV_ID}-app:5000/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Env-ID $ENV_ID;

        # Strip the /env/$ENV_ID prefix before forwarding
        rewrite ^/env/$ENV_ID/(.*) /\$1 break;
    }

    location /env/$ENV_ID/health {
        proxy_pass http://${ENV_ID}-app:5000/health;
        proxy_set_header Host \$host;
    }
}
NGINX_EOF

# Reload Nginx to pick up the new config
echo "→ Reloading Nginx..."
docker exec platform-nginx nginx -s reload
echo "  ✓ Nginx reloaded"

# ── Write state file atomically ───────────────────────────────────────────────
# Write to temp file first, then mv into place
# This prevents partial reads if the script crashes mid-write
echo "→ Writing state file..."
STATE_FILE="$ENVS_DIR/${ENV_ID}.json"
TEMP_FILE="$ENVS_DIR/.tmp_${ENV_ID}.json"

cat > "$TEMP_FILE" << JSON_EOF
{
    "id": "$ENV_ID",
    "name": "$ENV_NAME",
    "created_at": $CREATED_AT,
    "ttl_seconds": $TTL_SECONDS,
    "expires_at": $EXPIRES_AT,
    "status": "running",
    "app_port": $APP_PORT,
    "container_id": "$CONTAINER_ID",
    "log_shipper_pid": $LOG_PID
}
JSON_EOF

# Atomic move — prevents partial reads
mv "$TEMP_FILE" "$STATE_FILE"
echo "  ✓ State file written"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ Environment ready"
echo "  URL:     http://localhost/env/$ENV_ID/"
echo "  Health:  http://localhost/env/$ENV_ID/health"
echo "  Logs:    make logs ENV=$ENV_ID"
echo "  TTL:     ${TTL_MINUTES} minutes"
echo "  Expires: $(date -u -d @$EXPIRES_AT '+%Y-%m-%d %H:%M:%S UTC' 2>/dev/null || date -u -r $EXPIRES_AT '+%Y-%m-%d %H:%M:%S UTC')"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
# Connect container to platform network so Nginx can reach it
echo "→ Connecting to platform network..."
if docker network connect platform-network "${ENV_ID}-app"; then
    echo "  ✓ Connected to platform network"
else
    echo "  ✗ Failed to connect to platform network"
    exit 1
fi